CREATE DATABASE GlobalPayDB;
GO

USE GlobalPayDB;
GO

-- MOEDAS QUE O SISTEMA SUPORTA (FOCO EM HAITI E BRASIL)
CREATE TABLE Moedas (
	MoedaID CHAR(3) PRIMARY KEY,
	NomeMoeda VARCHAR(50) NOT NULL,
	Simbolo VARCHAR(5)
);

-- CADASTRO DO CLIENTE
CREATE TABLE Clientes (
	ClienteID INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) UNIQUE,
	DataCadastro DATETIME DEFAULT GETDATE(),
	Ativo BIT DEFAULT 1
);

-- CONTAS
CREATE TABLE Contas(
	ContaID INT IDENTITY(1,1) PRIMARY KEY,
	ClienteID INT NOT NULL,
	MoedaID CHAR(3) NOT NULL,
	Saldo DECIMAL(18, 2) DEFAULT 0.00,
	CONSTRAINT FK_CLIENTE FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID),
	CONSTRAINT FK_Moeda FOREIGN KEY (MoedaID) REFERENCES Moedas(MoedaID),
	CONSTRAINT FK_Saldo_Nao_Negativo CHECK (Saldo >= 0)
);

--Taxas de cambio 
CREATE TABLE CambioHistorico (
	CambioID INT IDENTITY(1,1) PRIMARY KEY,
	MoedaOrigem CHAR(3) NOT NULL,
	MoedaDestino CHAR(3) NOT NULL,
	Taxa DECIMAL(18,6) NOT NULL,
	DataReferencia DATETIME DEFAULT GETDATE()
);

-- REGISTRO DE TRANSAÇOES
CREATE TABLE Transacoes(
	TransacaoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ContaOrigemID INT NOT NULL,
	ContaDestinoID INT NOT NULL,
	ValorOriginal DECIMAL(18,2) NOT NULL,
	ValorFinal Decimal(18,6),
	TaxaAplicada DECIMAL(18,6),
	DataTransacao DATETIME DEFAULT GETDATE(),
	CONSTRAINT FK_Origem FOREIGN KEY (ContaOrigemID) REFERENCES Contas(ContaID),
	CONSTRAINT FK_Destino FOREIGN KEY (ContaDestinoID) REFERENCES Contas(ContaID)
	
);
GO